stages:
  - test
  - build

image: docker.dev.dszn.cz/doporucovani/gitlab-ci/debian:stretch

# This job is used to test a library.
jobslib-test:
  stage: test
  only:
    refs:
      - branches
      - /^jobslib-.*$/
  script:
    - python3 setup.py install
    - bash scripts/test.sh

# This job is used to build and release python library into http://pypi.kancelar.seznam.cz.
jobslib-build:
  stage: build
  only:
    refs:
      - /^jobslib-.*$/
  script:
    - echo -e "password=$PYPI_DOPORUCOVANI" >> /root/.pypirc
    - python3 setup.py sdist
    - twine upload -r sznpypi dist/*
